#!/bin/sh

WT_DIR='/home/ghz/repos/weather_tools'
DAT_DIR='/home/ghz/repos/mq_gases/data'

"${WT_DIR}/grab_48h" "${DAT_DIR}" gas_levels
/usr/bin/gnuplot /home/ghz/repos/mq_gases/mqs.gnuplot 2>&1 | /usr/bin/fgrep -v 'Warning: empty y range [0:0], adjusting to [-1:1]'
/usr/bin/rsync -ur --timeout=58 --exclude .git /home/ghz/repos/mq_gases/ wx0_sync:/wx0/mqs/ 2> /dev/null
